import {
  ClerkProvider,
  
} from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import { EcomNavbarComponent } from "@/components/ecom-navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <EcomNavbarComponent />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
