import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import { EcomNavbarComponent } from "@/components/ecom-navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { SignedOut, SignedIn } from "@clerk/nextjs";
import { LandingPageComponent } from "@/components/landing-page";
import { Analytics } from "@vercel/analytics/react";
import Head from "next/head";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Head>
            <link rel="icon" href="/favicon.ico" sizes="any" />
          </Head>
          <SignedOut>
            <LandingPageComponent />
          </SignedOut>
          <SignedIn>
            <EcomNavbarComponent />
            {children}
            <Analytics />
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
